# -*- coding:utf-8 -*-
"""
Created on 27 Jul 2011

@author: kris
"""
from coinpy.model.scripts.opcodes import *
from coinpy.model.scripts.vm.opcode_impl.reserved import op_not_implemented
from coinpy.model.scripts.vm.opcode_impl.pushdata import op_pushdata
from coinpy.model.scripts.vm.opcode_impl.stack import op_dup
from coinpy.model.scripts.vm.opcode_impl.bitwise import op_equal, op_equalverify
from coinpy.model.scripts.vm.opcode_impl.flow import op_verify
from coinpy.model.scripts.vm.opcode_impl.crypto import op_hash160, op_checksig

OPCODE_FUNCTIONS = {
    OP_0 : op_not_implemented,
    OP_PUSHDATA : op_pushdata, 
    OP_1NEGATE : op_not_implemented,
    OP_1 : op_not_implemented,
    OP_2 : op_not_implemented,
    OP_3 : op_not_implemented,
    OP_4 : op_not_implemented,
    OP_5 : op_not_implemented,
    OP_6 : op_not_implemented,
    OP_7 : op_not_implemented,
    OP_8 : op_not_implemented,
    OP_9 : op_not_implemented,
    OP_10 : op_not_implemented,
    OP_11 : op_not_implemented,
    OP_12 : op_not_implemented,
    OP_13 : op_not_implemented,
    OP_14 : op_not_implemented,
    OP_15 : op_not_implemented,
    OP_16 : op_not_implemented,
# Flow control 
    OP_NOP : op_not_implemented,
    OP_IF : op_not_implemented,
    OP_NOTIF : op_not_implemented,
    OP_ELSE : op_not_implemented,
    OP_ENDIF : op_not_implemented,
    OP_VERIFY : op_verify,
    OP_RETURN : op_not_implemented,
# Stack 
    OP_TOALTSTACK : op_not_implemented,
    OP_FROMALTSTACK : op_not_implemented,
    OP_IFDUP : op_not_implemented,
    OP_DEPTH : op_not_implemented,
    OP_DROP : op_not_implemented,
    OP_DUP : op_dup,
    OP_NIP : op_not_implemented,
    OP_OVER : op_not_implemented,
    OP_PICK : op_not_implemented,
    OP_ROLL : op_not_implemented,
    OP_ROT : op_not_implemented,
    OP_SWAP : op_not_implemented,
    OP_TUCK : op_not_implemented,
    OP_2DROP : op_not_implemented,
    OP_2DUP : op_not_implemented,
    OP_3DUP : op_not_implemented,
    OP_2OVER : op_not_implemented,
    OP_2ROT : op_not_implemented,
    OP_2SWAP : op_not_implemented,
# Splice 
    OP_CAT : op_not_implemented,
    OP_SUBSTR : op_not_implemented,
    OP_LEFT : op_not_implemented,
    OP_RIGHT : op_not_implemented,
    OP_SIZE : op_not_implemented,
# Bitwise logic 
    OP_INVERT : op_not_implemented,
    OP_AND : op_not_implemented,
    OP_OR : op_not_implemented,
    OP_XOR : op_not_implemented,
    OP_EQUAL : op_equal,
    OP_EQUALVERIFY : op_equalverify,
# Arithmetic
    OP_1ADD : op_not_implemented,
    OP_1SUB : op_not_implemented,
    OP_2MUL : op_not_implemented,
    OP_2DIV : op_not_implemented,
    OP_NEGATE : op_not_implemented,
    OP_ABS : op_not_implemented,
    OP_NOT : op_not_implemented,
    OP_0NOTEQUAL : op_not_implemented,
    OP_ADD : op_not_implemented,
    OP_SUB : op_not_implemented,
    OP_MUL : op_not_implemented,
    OP_DIV : op_not_implemented,
    OP_MOD : op_not_implemented,
    OP_LSHIFT : op_not_implemented,
    OP_RSHIFT : op_not_implemented,
    OP_BOOLAND : op_not_implemented,
    OP_BOOLOR : op_not_implemented,
    OP_NUMEQUAL : op_not_implemented,
    OP_NUMEQUALVERIFY : op_not_implemented,
    OP_NUMNOTEQUAL : op_not_implemented,
    OP_LESSTHAN : op_not_implemented,
    OP_GREATERTHAN : op_not_implemented,
    OP_LESSTHANOREQUAL : op_not_implemented,
    OP_GREATERTHANOREQUAL : op_not_implemented,
    OP_MIN : op_not_implemented,
    OP_MAX : op_not_implemented,
    OP_WITHIN : op_not_implemented,
# Crypto 
    OP_RIPEMD160 : op_not_implemented,
    OP_SHA1 : op_not_implemented,
    OP_SHA256 : op_not_implemented,
    OP_HASH160 : op_hash160,
    OP_HASH256 : op_not_implemented,
    OP_CODESEPARATOR : op_not_implemented,
    OP_CHECKSIG : op_checksig,
    OP_CHECKSIGVERIFY : op_not_implemented,
    OP_CHECKMULTISIG : op_not_implemented,
    OP_CHECKMULTISIGVERIFY : op_not_implemented,
# Pseudo-words 
    OP_PUBKEYHASH : op_not_implemented,
    OP_PUBKEY : op_not_implemented,
    OP_INVALIDOPCODE : op_not_implemented,
# Reserved words
    OP_RESERVED : op_not_implemented,
    OP_VER : op_not_implemented,
    OP_VERIF : op_not_implemented,
    OP_VERNOTIF : op_not_implemented,
    OP_RESERVED1 : op_not_implemented,
    OP_RESERVED2 : op_not_implemented,
    OP_NOP1 : op_not_implemented,
    OP_NOP2 : op_not_implemented,
    OP_NOP3 : op_not_implemented,
    OP_NOP4 : op_not_implemented,
    OP_NOP5 : op_not_implemented,
    OP_NOP6 : op_not_implemented,
    OP_NOP7 : op_not_implemented,
    OP_NOP8 : op_not_implemented,
    OP_NOP9 : op_not_implemented,
    OP_NOP10 : op_not_implemented    
}